import { getPages } from "@/sanity/sanity-utils";
import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: "My  Awesome Site!",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-400 via-red-500 to bg-purple-600 bg-clip-text text-transparent text-xl font-bold"
          >
            Simen
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.length
              ? pages.map((page) => (
                  <Link
                    key={page._id}
                    href={`/${page.slug}`}
                    className="hover:underline"
                  >
                    {page.title}
                  </Link>
                ))
              : null}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
